// <auto-generated />
using System;
using GrpcDemo.Product.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcDemo.Product.Infrastructure.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20221225180951_AddSeed")]
    partial class AddSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcDemo.Product.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d8abdec-67f7-481f-8eab-e3df947a9c01"),
                            ProductName = "Donnie Darko",
                            ProductPrice = 46.4m
                        },
                        new
                        {
                            Id = new Guid("3d889ad4-cdee-42c8-adf2-0419892b30ba"),
                            ProductName = "Çöküş",
                            ProductPrice = 76m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
